// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// stopFunc is an autogenerated mock type for the stopFunc type
type stopFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields:
func (_m *stopFunc) Execute() {
	_m.Called()
}
