// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import (
	domain "xendit-technical-assessment/pkg/domain"

	mock "github.com/stretchr/testify/mock"
)

// MarvelService is an autogenerated mock type for the MarvelService type
type MarvelService struct {
	mock.Mock
}

// GetCharacterDetails provides a mock function with given fields: _a0
func (_m *MarvelService) GetCharacterDetails(_a0 int) (domain.Character, error) {
	ret := _m.Called(_a0)

	var r0 domain.Character
	if rf, ok := ret.Get(0).(func(int) domain.Character); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(domain.Character)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCharacterIds provides a mock function with given fields:
func (_m *MarvelService) GetCharacterIds() ([]int, error) {
	ret := _m.Called()

	var r0 []int
	if rf, ok := ret.Get(0).(func() []int); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
